name: ci

on: workflow_dispatch
jobs:
  build-bin:
    name: ${{ matrix.kind }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind: ["ubuntu"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Cache docker registry
        uses: actions/cache@v3
        with:
          key: registry-${{ github.sha }}
          fail-on-cache-miss: true
          path: ${{ runner.temp }}/registry

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      - name: Start local Docker registry
        run: |
          # Docker save / load does not support multi-arch images.
          # This sets up a local registry that I can push the images to.
          docker run -d -p 5000:5000 -e 'REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry' -v '${{ runner.temp }}/registry:/var/lib/registry' registry:2

      - name: Login to Docker Hub
        if: github.repository == 'denoland/deno_docker'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Update tags
        if: github.repository == 'denoland/deno_docker'
        run: |
          docker buildx imagetools create -t denoland/deno:latest denoland/deno:2.2.9
          docker buildx imagetools create -t denoland/deno:debian denoland/deno:2.2.9
          docker buildx imagetools create -t denoland/deno:alpine denoland/deno:alpine-2.2.9
          docker buildx imagetools create -t denoland/deno:bin denoland/deno:bin-2.2.9
          docker buildx imagetools create -t denoland/deno:distroless denoland/deno:distroless-2.2.9
          docker buildx imagetools create -t denoland/deno:ubuntu denoland/deno:ubuntu-2.2.9
